/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-01-21 06:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class insertMembers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원 가입</title>\n");
      out.write("\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/FE/Member.css\">\n");
      out.write("<!-- 제이쿼리 적용-->\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("<!-- 테일윈드 적용-->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css\">\n");
      out.write("<!-- 폰트어썸 적용-->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"con mx-auto flex justify-center\">\n");
      out.write("  <section class=\"sign-up-box flex justify-center \">\n");
      out.write("    <div class=\"menu-1\">\n");
      out.write("      <!-- 로고 부분 -->\n");
      out.write("      <a href=\"/FE/index.html\" class=\"logo\">\n");
      out.write("        <span>PROJECT<br>AOE</span>\n");
      out.write("      </a>\n");
      out.write("<form method = \"post\" action = \"insertMembers.member\">\n");
      out.write("      <!-- 글자 부분 -->\n");
      out.write("      <h1>회원가입</h1>\n");
      out.write("      <!-- 입력란 부분 -->\n");
      out.write("      <div class=\"input-box\">\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("          <p>아이디</p>\n");
      out.write("          <input onfocus=\"$(this).addClass('focused');\" type=\"text\" name=\"id\" class=\"input-box__e-mail  border w-full rounded px-4 py-3 block\" placeholder=\"아이디를 입력해주세요.\" required value>\n");
      out.write("          <div class=\"empty\">아이디를 입력해주세요.</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("          <p>비밀번호</p>\n");
      out.write("          <input onfocus=\"$(this).addClass('focused');\" type=\"password\" name=\"pw\" class=\"border w-full rounded px-4 py-3 block\" placeholder=\"비밀번호를 입력해주세요\" required value>\n");
      out.write("          <div class=\"empty\">비밀번호를 입력해주세요.</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("          <p>이메일</p>\n");
      out.write("          <input onfocus=\"$(this).addClass('focused');\" type=\"email\" name=\"email\" class=\"input-box__e-mail  border w-full rounded px-4 py-3 block\" placeholder=\"이메일 형식으로 입력해주세요.\" required value>\n");
      out.write("          <div class=\"empty\">이메일을 입력해주세요.</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("        <!--하단 확인버튼 부분-->\n");
      out.write("        <button class=\"ok-button flex justify-center w-full\" href=\"MemberCreate.html\">\n");
      out.write("         <a href=\"LoginForm.jsp\">\n");
      out.write("           <span class=\"flex\">확인</span>\n");
      out.write("         </a>\n");
      out.write("        </button>\n");
      out.write("        \n");
      out.write("<br>\n");
      out.write("<a href=\"http://localhost:8081/FE/index.html\"> 홈으로 </a>\n");
      out.write("      </div>\n");
      out.write("  </section>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("<h1>새 맴버 등록</h1>\n");
      out.write("<form method = \"post\" action = \"insertMembers.member\">\n");
      out.write("<table border=\"1\" cellpadding=\"10\" cellspacing=\"0\">\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write(" <td bgcolor=\"orange\" align=\"center\">id</td>\n");
      out.write(" <td><input type=\"text\" name=\"id\" ></td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write(" <td bgcolor=\"orange\" align = \"center\"> password </td> \n");
      out.write(" <td> <input type=\"text\" name = \"pw\" size=\"10\"></td>\n");
      out.write("</tr>\n");
      out.write(" \n");
      out.write(" <tr>\n");
      out.write(" <td  bgcolor=\"orange\" align = \"center\"> email </td> \n");
      out.write(" <td> <textarea name=\"email\" rows=\"10\" cols=\"40\"></textarea></td>\n");
      out.write(" </tr>\n");
      out.write("\n");
      out.write(" \n");
      out.write("<tr>\n");
      out.write("<td colspan = \"2\" align = \"center\"> <input type=\"submit\" value=\"새 맴버 등록\"></td> \n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<br> <a href=\"http://localhost:8081/FE/index.html\"> 홈으로 </a>\n");
      out.write("<p /> <a href= \"getMembersList.member\"> 맴버 목록 </a>\n");
      out.write(" -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
